config/routes.rb
OrcidLinkedGraph::Application.routes.draw do
  resources :orcids
  match '/namesearch/:namesearch' => 'orcids#index'
  match '/titlesearch/:titlesearch' => 'orcids#index'

end

app/models/orcid.rb
class Orcid < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/orcids_controller.rb
class OrcidsController < ApplicationController
  # GET /orcids
  # GET /orcids.json
  def index
    @orcids = Orcid.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orcids }
    end
  end

  # GET /orcids/1
  # GET /orcids/1.json
  def show
    @orcid = find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @orcid }
    end
  end

  # GET /orcids/new
  # GET /orcids/new.json
  def new
    @orcid = Orcid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orcid }
    end
  end

  # GET /orcids/1/edit
  def edit
    @orcid = Orcid.find(params[:id])
  end

  # POST /orcids
  # POST /orcids.json
  def create
    @orcid = Orcid.new(params[:orcid])

    respond_to do |format|
      if @orcid.save
        format.html { redirect_to @orcid, notice: 'Orcid was successfully created.' }
        format.json { render json: @orcid, status: :created, location: @orcid }
      else
        format.html { render action: "new" }
        format.json { render json: @orcid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orcids/1
  # PUT /orcids/1.json
  def update
    @orcid = Orcid.find(params[:id])

    respond_to do |format|
      if @orcid.update_attributes(params[:orcid])
        format.html { redirect_to @orcid, notice: 'Orcid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @orcid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orcids/1
  # DELETE /orcids/1.json
  def destroy
    @orcid = Orcid.find(params[:id])
    @orcid.destroy

    respond_to do |format|
      format.html { redirect_to orcids_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orcids_helper.rb
module OrcidsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OrcidLinkedGraph</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orcids/_form.html.erb
<%= form_for(@orcid) do |f| %>
  <% if @orcid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orcid.errors.count, "error") %> prohibited this orcid from being saved:</h2>

      <ul>
      <% @orcid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orcids/edit.html.erb
<h1>Editing orcid</h1>

<%= render 'form' %>

<%= link_to 'Show', @orcid %> |
<%= link_to 'Back', orcids_path %>

app/views/orcids/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Orcid / PubMed Search Visualization - OR2013</title>

<!-- CSS Files -->
<link type="text/css" href="css/base.css" rel="stylesheet" />
<link type="text/css" href="css/Spacetree.css" rel="stylesheet" />

<!--[if IE]><script language="javascript" type="text/javascript" src="../../Extras/excanvas.js"></script><![endif]-->

<!-- JIT Library File -->
<script language="javascript" type="text/javascript" src="jit.js"></script>

<script>
var labelType, useGradients, nativeTextSupport, animate;

(function() {
  var ua = navigator.userAgent,
      iStuff = ua.match(/iPhone/i) || ua.match(/iPad/i),
      typeOfCanvas = typeof HTMLCanvasElement,
      nativeCanvasSupport = (typeOfCanvas == 'object' || typeOfCanvas == 'function'),
      textSupport = nativeCanvasSupport 
        && (typeof document.createElement('canvas').getContext('2d').fillText == 'function');
  //I'm setting this based on the fact that ExCanvas provides text support for IE
  //and that as of today iPhone/iPad current text support is lame
  labelType = (!nativeCanvasSupport || (textSupport && !iStuff))? 'Native' : 'HTML';
  nativeTextSupport = labelType == 'Native';
  useGradients = nativeCanvasSupport;
  animate = !(iStuff || !nativeCanvasSupport);
})();

var Log = {
  elem: false,
  write: function(text){
    if (!this.elem) 
      this.elem = document.getElementById('log');
    this.elem.innerHTML = text;
    this.elem.style.left = (500 - this.elem.offsetWidth / 2) + 'px';
  }
};


function init(){
    //alert(getParamValue('searchName'));
    //jquery use getJSON/get?

    //init data
    // which search are we running / what params? -- FIRST, totally fake out data JIC/forTesting! :)
    //#'http://localhost:3000/namesearch.json?' + params['namesearch'].gsub(" ", "%20")
    <% if params[:oid]
        url = "http://puffin.ecs.soton.ac.uk/cgi/get_pubs?oid=#{params[:oid]}"
    elsif params[:doi]
        url = "http://puffin.ecs.soton.ac.uk/cgi/get_pubs?doi=#{params[:doi]}"
    elsif params[:pmid]
        url = "http://puffin.ecs.soton.ac.uk/cgi/get_pubs?pubmedid=#{params[:pmid]}"
    elsif params[:fn]
        url = "http://puffin.ecs.soton.ac.uk/cgi/get_pubs?fn=#{params[:fn]}&ln=#{params[:ln]}"
    else
        url = 'http://localhost:3000/titlesearch.json?' + params['titlesearch'].gsub(" ", "%20")
    end %>

    console.log("<%=url%>")

    var json = <%= Net::HTTP.get(URI.parse(url)).html_safe %>;
    
    //preprocess subtrees orientation
    var arr = json.children, len = arr.length;
    for(var i=0; i < len; i++) {
        //split half left orientation
      if(i < len / 2) {
            arr[i].data.$orn = 'left';
            $jit.json.each(arr[i], function(n) {
                n.data.$orn = 'left';
            });
        } else {
        //half right
            arr[i].data.$orn = 'right';
            $jit.json.each(arr[i], function(n) {
                n.data.$orn = 'right';
            });
        }
    }
    //end
    //grab radio button
    var normal = $jit.id('s-normal');
    //init Spacetree
    //Create a new ST instance
    var st = new $jit.ST({
        //id of viz container element
        injectInto: 'infovis',
        //multitree
          multitree: true,
        //set duration for the animation
        duration: 800,
        //set animation transition type
        transition: $jit.Trans.Quart.easeInOut,
        //set distance between node and its children
        levelDistance: 40,
        //sibling and subtrees offsets
        siblingOffset: 3,
        subtreeOffset: 3,
        //set node and edge styles
        //set overridable=true for styling individual
        //nodes or edges
        Node: {
            height: 105,
            width: 165,
            type: 'rectangle',
            color: '#aaa',
            overridable: true,
            //set canvas specific styles
            //like shadows
            CanvasStyles: {
              shadowColor: '#ccc',
              shadowBlur: 10
            }
        },
        Edge: {
            type: 'bezier',
            lineWidth: 2,
            overridable: true
        },
        
        onBeforeCompute: function(node){
            Log.write("loading " + node.name);
        },
        
        onAfterCompute: function(){
            Log.write("done");
        },
        
        //This method is called on DOM label creation.
        //Use this method to add event handlers and styles to
        //your node.
        onCreateLabel: function(label, node){
            label.id = node.id;
            label.innerHTML = node.name.substring(0,90);
                if (node.data.orcid != undefined)
                {
                    label.innerHTML = label.innerHTML + "<br>&nbsp;" + node.data.orcid ;
                }

            label.innerHTML = label.innerHTML + '<br><div style="font-size:.8em;position: absolute; bottom: 7px;">';
            if (node.data.target != undefined) {
                label.innerHTML = label.innerHTML + '<a href="' + node.data.target + '" target="_blank">Article</a>'; 
            } 
            label.innerHTML = label.innerHTML + '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href=' + '"http://localhost:8080/rest/fcr:search?q=' + node.name + '" target="_blank">Search Fedora</a>'
             + '</div>'
            label.onclick = function(){
                v = node.name.replace(/\./g, '')
                console.log(node.data)
                if (node.data.orcid != undefined) {
                    location.href = "/namesearch/search?oid=" + node.data.orcid; 
                }
                else if (node.data.type == 'person') {
                    location.href = "/namesearch/search?=" + v; 
                } else if (node.data.id_type == 'doi') {
                    //#10.1111/j.1365-2567.2008.02825.x
                    location.href = "/namesearch/search?doi=" + node.data.id; 
                } else if (node.data.id_type == 'pmid') {
                    //#10.1111/j.1365-2567.2008.02825.x
                    location.href = "/namesearch/search?pmid=" + node.data.id; 
                } else {
                    //location.href = "/namesearch/search?fn=" + node.data.fn + "&ln=" + node.data.ln; 
                }
                //st.setRoot(node.id, 'animate');
            };
            //set label styles
            var style = label.style;
            console.log(node);
            style.height = 105 + 'px';
            style.width = 160 + 'px';
            style.cursor = 'pointer';
            style.color = '#333';
            style.fontSize = '0.8em';
            style.textAlign= 'center';
            style.paddingTop = '10px';
        },
        
        //This method is called right before plotting
        //a node. It's useful for changing an individual node
        //style properties before plotting it.
        //The data properties prefixed with a dollar
        //sign will override the global node style properties.
        onBeforePlotNode: function(node){
            //add some color to the nodes in the path between the
            //root node and the selected node.
            if (node.selected) {
                //node.data.$color = "#ff7";
                // could change node height here to be min or something? node.data.$height = 250;
            }
            else {
                delete node.data.$color;
                //if the node belongs to the last plotted level
                if(!node.anySubnode("exist")) {
                    //count children number
                    var count = 0;
                    node.eachSubnode(function(n) { count++; });
                    //assign a node color based on
                    //how many children it has
                    //node.data.$color = ['#aaa', '#baa', '#caa', '#daa', '#eaa', '#faa'][count];
                }
            }

            console.log(node.data.type)

            if (node.data.type == 'person') {
                node.data.$color = '#ee8';                
            }
            else if (node.data.type == 'orcid') {
                node.data.$color = '#ff7';
            } else {
                node.data.$color = '#baa';
            }
        },
        
        //This method is called right before plotting
        //an edge. It's useful for changing an individual edge
        //style properties before plotting it.
        //Edge data proprties prefixed with a dollar sign will
        //override the Edge global style properties.
        onBeforePlotLine: function(adj){
            if (adj.nodeFrom.selected && adj.nodeTo.selected) {
                adj.data.$color = "#eed";
                adj.data.$lineWidth = 3;
            }
            else {
                delete adj.data.$color;
                delete adj.data.$lineWidth;
            }
        }
    });
    //load json data
    st.loadJSON(json);
    //compute node positions and layout
    st.compute('end');
    st.select(st.root);
    //end
}

    function getParamValue(parameter)   
    {   
        var urlParamString = location.search.substring(1, location.search.length);  
      
        var paramValue = false;  
        var params = urlParamString.split("&");  
          
        for (i=0; i<params.length;i++)   
        {  
            paramName = params[i].substring(0,params[i].indexOf('='));  
            if (paramName == parameter)   
            {  
                paramValue = params[i].substring(params[i].indexOf('=')+1)  
            }  
              
        }  
          
        if (paramValue)
        {  
            return paramValue.replace(/%20/g, ' ');  
        }  
        else   
        {  
            return null;  
        }  
    }  
      
</script>


</head>


<body onload="init();">
<div id="container">
    <div id="left-container">
        <div class="text">

        Orcid data here?
                
        </div>

    <div id="id-list"></div>
    </div>

    <div id="center-container">
        <div id="infovis"></div>    
        <div style="display:none" id="log"></div>
    </div>
</div>

</body>
</html>

app/views/orcids/new.html.erb
<h1>New orcid</h1>

<%= render 'form' %>

<%= link_to 'Back', orcids_path %>

app/views/orcids/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_orcid_path(@orcid) %> |
<%= link_to 'Back', orcids_path %>